# Generated by Django 4.2.1 on 2023-05-25 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_employee_personal_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0003_alter_question_options_alter_answer_prompt_ar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assessment',
            new_name='Audit',
        ),
    ]
