# Generated by Django 4.2.1 on 2023-05-25 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_employee_personal_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0004_rename_assessment_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('question', 'display_order', '-weight')},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('audit', 'display_order')},
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.AddField(
            model_name='answer',
            name='display_order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='question',
            name='audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.audit', verbose_name='Audit'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='clients.organization', verbose_name='Created For'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_audits', to='assessment.audit', verbose_name='Derived From'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_audits', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
