# Generated by Django 4.2.1 on 2024-01-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_alter_answer_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ("audit", "section", "display_order")},
        ),
        migrations.AddField(
            model_name="audit",
            name="root_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit",
                to="assessment.section",
                verbose_name="Root Section",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Display Order"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Display Order"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Display Order"
            ),
        ),
        migrations.CreateModel(
            name="AuditFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.FileField(max_length=512, upload_to="uploads/")),
                (
                    "audit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="assessment.audit",
                        verbose_name="Audit",
                    ),
                ),
            ],
        ),
    ]
