# Generated by Django 4.2.1 on 2024-02-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0006_alter_question_options_audit_root_section_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audit",
            name="root_section",
        ),
        migrations.AlterField(
            model_name="answer",
            name="prompt_ar",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Prompt (AR)"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="prompt_en",
            field=models.CharField(max_length=256, verbose_name="Prompt (EN)"),
        ),
        migrations.AlterField(
            model_name="audit",
            name="description_ar",
            field=models.TextField(blank=True, verbose_name="Description (AR)"),
        ),
        migrations.AlterField(
            model_name="audit",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (EN)"),
        ),
        migrations.AlterField(
            model_name="audit",
            name="title_ar",
            field=models.CharField(
                max_length=512, verbose_name="Title (AR)"
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="title_en",
            field=models.CharField(
                max_length=512, verbose_name="Title (EN)"
            ),
        ),

    ]
