# Generated by Django 4.2.1 on 2024-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment",
            "0007_remove_audit_root_section_alter_answer_prompt_ar_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")],
                default="DRAFT",
                max_length=128,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="title_ar",
            field=models.CharField(
                max_length=512, verbose_name="Title (AR)"
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="title_en",
            field=models.CharField(
                max_length=512, verbose_name="Title (EN)"
            ),
        ),
    ]
