# Generated by Django 4.2.1 on 2024-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0008_audit_status_alter_audit_title_ar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="title_ar",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Title (AR)"
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="title_en",
            field=models.CharField(
                max_length=512, verbose_name="Title (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="title_ar",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Title (AR)"
            ),
        ),
    ]
