# Generated by Django 4.2.1 on 2024-04-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0009_alter_audit_title_ar_alter_audit_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="weight",
            field=models.FloatField(
                blank=True,
                help_text="Empty wight indicate N/A answers which are not going to be calculated in the total score",
                null=True,
                verbose_name="Weight",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="title_en",
            field=models.CharField(
                max_length=512, verbose_name="Title (EN)"
            ),
        ),
    ]
