# Generated by Django 4.2.1 on 2024-06-22 07:42

import constrainedfilefield.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_alter_answer_weight_alter_audit_title_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('audit', 'section', 'display_order', 'prompt_ar', 'prompt_en')},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('display_order', 'title_ar', 'title_en')},
        ),
        migrations.AddField(
            model_name='question',
            name='is_bonus',
            field=models.BooleanField(default=False, verbose_name='Is a Bonus Question?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('TEMPLATE', 'Template'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=128, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='title_en',
            field=models.CharField(max_length=512, unique=True, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='type',
            field=models.CharField(choices=[('RESTAURANTS', 'Restaurants'), ('HOTELS', 'Hotels'), ('PILGRIMS_CENTER', 'Pilgrims Center'), ('MISC', 'Miscellaneous')], max_length=128, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='type',
            field=models.CharField(choices=[('PICTURE', 'Picture'), ('VIDEO', 'Video'), ('TEXT_NOTE', 'Note (Text only)'), ('misc', 'Miscellaneous')], max_length=256, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='uploaded_file',
            field=constrainedfilefield.fields.file.ConstrainedFileField(blank=True, content_types=['application/pdf', 'image/png', 'image/bmp', 'image/jpg', 'image/jpeg', 'image/gif'], max_upload_size=2000000, mime_lookup_length=4096, null=True, upload_to='evidence', verbose_name='Attachment'),
        ),
    ]
