# Generated by Django 4.2.13 on 2024-06-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_question_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='inspection_date',
            field=models.DateTimeField(blank=True, help_text='Date/time of the inspection visit', null=True, verbose_name='Inspection Date'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Write a meaningful and descriptive title (or name) for this audit in Arabic.', max_length=512, verbose_name='Title (AR)'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='title_en',
            field=models.CharField(help_text='Write a meaningful and descriptive title (or name) for this audit in English.', max_length=512, verbose_name='Title (EN)'),
        ),
    ]
