# Generated by Django 4.2.1 on 2023-05-11 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('CEO', 'CEO'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('DEPARTMENT_HEAD', 'Department Head'), ('SUPERVISOR', 'Supervisor'), ('SECRETARY', 'Secretary'), ('COOK', 'Cook'), ('WORKER', 'Worker'), ('OTHER', 'Other')], max_length=128, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Associated User'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=512, verbose_name='Title (AR)')),
                ('title_en', models.CharField(max_length=512, verbose_name='Title (EN)')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='clients.organization', verbose_name='Department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='clients.department', verbose_name='Department'),
        ),
    ]
