# Generated by Django 4.2.1 on 2023-05-24 10:14

import constrainedfilefield.fields.file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_employee_job_title_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='personal_picture',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=['image/png', 'image/bmp', 'image/jpg', 'image/jpeg', 'image/gif'], max_upload_size=512000, mime_lookup_length=4096, null=True, upload_to='employees', verbose_name='Personal Picture'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_on_map',
            field=models.TextField(blank=True, verbose_name='Address on Map'),
        ),
        migrations.AddField(
            model_name='organization',
            name='commercial_licence',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=['application/pdf', 'image/png', 'image/bmp', 'image/jpg', 'image/jpeg', 'image/gif'], max_upload_size=2048000, mime_lookup_length=4096, null=True, upload_to='licences', verbose_name='Commercial Licence'),
        ),
        migrations.AddField(
            model_name='organization',
            name='commercial_licence_end_date',
            field=models.DateField(null=True, verbose_name='Commercial Licence End Date'),
        ),
        migrations.AddField(
            model_name='organization',
            name='commercial_registration_no',
            field=models.CharField(default='NONE', max_length=256, unique=True, verbose_name='Commercial Registration Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=['image/png', 'image/bmp', 'image/jpg', 'image/jpeg', 'image/gif'], max_upload_size=512000, mime_lookup_length=4096, null=True, upload_to='logos', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='clients.organization', verbose_name='Organization'),
        ),
    ]
