# Generated by Django 4.2.1 on 2024-02-27 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_employee_personal_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=512, verbose_name="Task Description"),
                ),
                (
                    "create_date",
                    models.DateField(null=True, verbose_name="Create Date"),
                ),
                ("due_date", models.DateField(null=True, verbose_name="Due Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=128,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, max_length=512, verbose_name="Notes"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_tasks",
                        to="clients.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_tasks",
                        to="assessment.question",
                        verbose_name="Question",
                    ),
                ),
            ],
        ),
    ]
