# Generated by Django 4.2.1 on 2024-03-04 18:41

import constrainedfilefield.fields.file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_for",
                to="clients.employee",
                verbose_name="Manager",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=constrainedfilefield.fields.file.ConstrainedFileField(
                blank=True,
                content_types=["application/pdf"],
                max_upload_size=2000000,
                mime_lookup_length=4096,
                null=True,
                upload_to="tasks",
            ),
        ),
    ]
