# Generated by Django 4.2.1 on 2024-04-06 19:46

import constrainedfilefield.fields.file
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0005_employee_manager_task_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="title_ar",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Title (AR)"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="job_title",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO"),
                    ("OWNER", "Owner"),
                    ("HR", "HR"),
                    ("MANAGER", "Manager"),
                    ("DEPARTMENT_HEAD", "Department Head"),
                    ("SUPERVISOR", "Supervisor"),
                    ("SECRETARY", "Secretary"),
                    ("COOK", "Cook"),
                    ("WORKER", "Worker"),
                    ("OTHER", "Other"),
                ],
                max_length=128,
                verbose_name="Job Title",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="personal_picture",
            field=constrainedfilefield.fields.file.ConstrainedFileField(
                blank=True,
                content_types=[
                    "image/png",
                    "image/bmp",
                    "image/jpg",
                    "image/jpeg",
                    "image/gif",
                ],
                max_upload_size=512000,
                mime_lookup_length=4096,
                null=True,
                upload_to="employees",
                verbose_name="Personal Picture",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Associated User",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=constrainedfilefield.fields.file.ConstrainedFileField(
                blank=True,
                content_types=[
                    "image/png",
                    "image/bmp",
                    "image/jpg",
                    "image/jpeg",
                    "image/gif",
                ],
                max_upload_size=512000,
                mime_lookup_length=4096,
                null=True,
                upload_to="logos",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_ar",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Name (AR)"
            ),
        ),
    ]
